- name: single branch pipeline setup
  ansible.biultin.import_task:
    file: sp_jobs.yml
  loop: "{{sp_jobs}}"

- name: multy branch pipeline setup
  ansible.biultin.import_task:
    file: mp_jobs.yml
  loop: "{{mp_jobs}}"
